---
- name: Run tests
  block:
    - name: Run TestWorkSubmitWithTLSClient test
      ansible.builtin.command:
        cmd: make test
        chdir: /home/{{ ansible_user }}/receptor
      register: test_work_submit_with_tls_client_output
    - name: Assert test passed
      ansible.builtin.assert:
        that:
          - "'FAIL' not in test_work_submit_with_tls_client_output.stdout"
  always:
    - name: Log test results
      when: test_work_submit_with_tls_client_output is defined
      block:
        - name: Create log file
          ansible.builtin.file:
            path: "{{ run_tests_outfile_path }}"
            state: touch
          delegate_to: localhost
        - name: Log test output to file
          ansible.builtin.copy:
            dest: "{{ run_tests_outfile_path }}"
            content: "{{ test_work_submit_with_tls_client_output.stdout }}"
            mode: "0755"
          delegate_to: localhost
