---
- name: Uninstall Go
  become: true
  when: "'go' in ansible_facts.packages"
  block:
    - name: Yum uninstall golang
      ansible.builtin.yum:
        name: golang
        state: absent
    - name: Unset GOPATH
      block:
        - name: Remove Go dir
          ansible.builtin.file:
            path: /home/{{ ansible_user }}/go
            state: absent
        - name: Remove path from bashrc
          ansible.builtin.lineinfile:
            dest: /home/{{ ansible_user }}/.bashrc
            state: absent
            regexp: "^{{ item }}"
          with_items:
            - export GOPATH=$HOME/go
            - export PATH=$PATH:/usr/local/go/bin
        - name: Source bashrc
          become: false
          ansible.builtin.shell: source /home/{{ ansible_user }}/.bashrc
- name: Uninstall Receptor
  when: "`receptor` in ansible_facts.pacages"
  block:
    - name: Unlink Receptor bin
      become: true
      ansible.builtin.file:
        src: /home/{{ ansible_user }}/receptor/receptor
        dest: /usr/local/bin/receptor
        state: absent
    - name: Uninstall make
      become: true
      when: ansible_distribution != "Ubuntu"
      ansible.builtin.yum:
        name: make
        state: absent
    - name: Delete Receptor repo
      ansible.builtin.file:
        state: absent
        path: /home/{{ ansible_user }}/receptor
- name: Uninstall Kind
  become: true
  ansible.builtin.file:
    state: absent
    path: /usr/local/bin/kind
- name: Delete user@.service.d dir
  become: true
  ansible.builtin.file:
    state: absent
    path: /etc/systemd/system/user@.service.d
- name: Uninstall dnf-plugins.core
  ansible.builtin.yum:
    name: dnf-plugins-core
    state: absent
- name: Install docker
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
- name: Remove user from Docker group
  become: true
  ansible.builtin.command: gpasswd -d docker
- name: Delete iptables.conf
  become: true
  ansible.builtin.file:
    state: absent
    path: /etc/modules-load.d/iptables.conf
- name: Delete kubernetes.repo
  become: true
  ansible.builtin.file:
    state: absent
    path: /etc/yum.repos.d/kubernetes.repo
- name: Install kubectl
  become: true
  ansible.builtin.yum:
    name: kubectl
    state: absent
