---
- name: Check packages
  package_facts:
    manager: auto
- name: Setup specific system
  block:
    - name: Setup RHEL
      when: ansible_distribution == "RedHat"
      ansible.builtin.import_tasks:
        file: rhel.yml
    - name: Setup Fedora
      when: ansible_distribution == "Fedora"
      ansible.builtin.import_tasks:
        file: fedora.yml
    - name: Setup Ubuntu
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.import_tasks:
        file: ubuntu.yml